name: "🐞 Bug or error report"
title: "[BUG] <title>"
description: "Report an anomaly or unexpected behavior with a sample from this repository."
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the following details about the issue you encountered.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: "name or e-mail"
    validations:
      required: true

  - type: input
    id: when
    attributes:
      label: Date of finding(s)
      description: When did you bump into the bug?
      placeholder: "ex. 2023-08-02"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the observed behavior, why do you think your finding(s) was a bug?
      placeholder: "Tell us what you saw!"
    validations:
      required: true

  - type: dropdown
    id: criticality
    attributes:
      label: Assess the criticality of the issue
      options:
        - Critical
        - High
        - Moderate
        - Low
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Let me help you decide the correct rating:   
        
        **Critical** - The bug causes a complete system crash, data loss, or security breach, making the software unusable or poses a significant risk to users.
        
        **High** - The bug causes severe functionality issues, frequent crashes, or data corruption, impacting critical parts of the software.
        
        **Medium** - The bug causes moderate functionality issues, intermittent crashes, or minor data corruption, affecting non-critical parts of the software.
        
        **Low** - The bug causes minor functionality issues, cosmetic glitches, or minor inconveniences, not affecting critical aspects of the software.

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you reproduce this? Please provide as much step-by-step detail as possible. Screenshots, additonal files are very welcome as well!
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen when the reproduce steps are followed? Screenshots, additonal files are very welcome as well!
      placeholder: "Tell us what you expected to see!"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Any suggestions for fix
      description: Provide technical or high-level suggestions for the fix
      placeholder: "ex. Set the screen brightness above 55% to provide better visibility for the texts."
    validations:
      required: false
